spring:
  application:
    name: filmes 
jwt:
  signerKey: 5a47396f36906c32572a4f7b88b61fef554a04f9439cfae17f97b04c6b7d86a3
openrouter:
  api-key: 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